-- Generated from lib/data/services.ts, lib/data/plans.ts, and messages/en.json —
-- do not hand-edit. Re-run `node --experimental-strip-types scripts/generate-seed-sql.cjs`
-- after changing that source data.

truncate table public.services, public.service_categories, public.subscription_tiers restart identity cascade;

insert into public.service_categories (slug, name, description, icon, sort_order) values ('surgery', 'Surgery & Procedures', 'Our surgical suite is equipped for everything from routine sterilizations to complex soft-tissue and emergency procedures, with full pre-anaesthetic screening and dedicated post-op monitoring for every patient.', 'Scissors', 0);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('preventive-care', 'Primary & Preventive Care', 'The foundation of a long, healthy life — core and lifestyle vaccinations, wellness exams, parasite prevention, microchipping, and health certificates for travel or breed registration.', 'ShieldPlus', 1);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('dental', 'Dental Services', 'Dental disease affects most pets by age three. We offer ultrasonic scaling and polishing, full-mouth dental radiographs, and extractions under monitored anaesthesia.', 'Sparkles', 2);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('diagnostics', 'Laboratory & Diagnostics', 'Our in-house lab returns most bloodwork and urinalysis results within the hour, so treatment decisions don''t wait on a courier.', 'FlaskConical', 3);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('imaging', 'Imaging', 'Digital X-ray and ultrasound equipment on site means faster, clearer answers for injuries, swallowed objects, and internal medicine cases — no referral wait.', 'ScanLine', 4);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('orthopedics', 'Orthopedics', 'From cranial cruciate ligament injuries to fracture stabilization and spinal cases, our orthopedic service pairs surgical expertise with a structured rehab plan.', 'Bone', 5);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('endoscopy', 'Endoscopy', 'Bronchoscopy and gastroscopy let us investigate chronic coughing, swallowing difficulty, or a suspected foreign body without open surgery in many cases.', 'Search', 6);
insert into public.service_categories (slug, name, description, icon, sort_order) values ('emergency', 'Emergency Care', 'Accidents don''t wait for an appointment. We prioritize acute cases for same-day stabilization and treatment, with an after-hours line for existing clients.', 'Siren', 7);

insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'spay-neuter', 'Spay / Neuter', 'Routine sterilization with pre-anaesthetic bloodwork and take-home pain plan.', 220, 420, 90 from public.service_categories where slug = 'surgery';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'soft-tissue-surgery', 'Soft-Tissue Surgery', 'Mass removals, wound repair, and abdominal procedures.', 450, 1800, 120 from public.service_categories where slug = 'surgery';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'post-op-care-plan', 'Post-Op Care Plan', 'Suture check, pain management review, and recovery monitoring.', 60, 120, 30 from public.service_categories where slug = 'surgery';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'wellness-exam', 'Wellness Exam', 'Full nose-to-tail check-up with a licensed veterinarian.', 55, 90, 30 from public.service_categories where slug = 'preventive-care';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'vaccination-package', 'Vaccination Package', 'Core + lifestyle vaccines tailored to age and risk.', 40, 150, 20 from public.service_categories where slug = 'preventive-care';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'puppy-kitten-starter-visit', 'Puppy & Kitten Starter Visit', 'First-visit exam, deworming, and vaccine schedule planning.', 70, 110, 40 from public.service_categories where slug = 'preventive-care';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'microchipping-id', 'Microchipping & ID', 'Permanent ID chip with registry enrollment.', 35, 55, 15 from public.service_categories where slug = 'preventive-care';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'dental-cleaning-polish', 'Dental Cleaning & Polish', 'Ultrasonic scaling and polishing under anaesthesia.', 280, 550, 90 from public.service_categories where slug = 'dental';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'dental-x-rays', 'Dental X-Rays', 'Full-mouth radiographs to catch disease below the gumline.', 90, 150, 30 from public.service_categories where slug = 'dental';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'tooth-extraction', 'Tooth Extraction', 'Simple to surgical extractions with pain management.', 120, 400, 60 from public.service_categories where slug = 'dental';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'bloodwork-panel', 'Bloodwork Panel', 'Complete blood count and chemistry panel, in-house results.', 90, 220, 45 from public.service_categories where slug = 'diagnostics';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'urinalysis', 'Urinalysis', 'Screening for kidney, bladder, and metabolic issues.', 45, 80, 30 from public.service_categories where slug = 'diagnostics';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'rapid-test-panels', 'Rapid Test Panels', 'Parvo, heartworm, tick-borne disease, and FeLV/FIV screening.', 40, 95, 20 from public.service_categories where slug = 'diagnostics';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'digital-radiography', 'Digital Radiography', 'High-resolution X-ray imaging with same-day read.', 110, 260, 30 from public.service_categories where slug = 'imaging';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'abdominal-ultrasound', 'Abdominal Ultrasound', 'Non-invasive imaging for organs and soft tissue.', 180, 350, 45 from public.service_categories where slug = 'imaging';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'orthopedic-consultation', 'Orthopedic Consultation', 'Lameness exam with imaging referral plan.', 85, 140, 40 from public.service_categories where slug = 'orthopedics';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'cruciate-acl-repair', 'Cruciate (ACL) Repair', 'Surgical stabilization for cranial cruciate ligament injuries.', 1800, 3800, 150 from public.service_categories where slug = 'orthopedics';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'fracture-repair', 'Fracture Repair', 'Stabilization and fixation for fractures.', 900, 3200, 150 from public.service_categories where slug = 'orthopedics';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'gastroscopy', 'Gastroscopy', 'Camera-guided exam of the oesophagus and stomach.', 450, 950, 60 from public.service_categories where slug = 'endoscopy';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'bronchoscopy', 'Bronchoscopy', 'Airway scoping for chronic cough or breathing issues.', 450, 950, 60 from public.service_categories where slug = 'endoscopy';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'foreign-body-retrieval', 'Foreign Body Retrieval', 'Non-surgical removal of swallowed objects where possible.', 500, 1100, 75 from public.service_categories where slug = 'endoscopy';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'emergency-exam', 'Emergency Exam', 'Priority triage and stabilization exam.', 120, 180, 30 from public.service_categories where slug = 'emergency';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'overnight-monitoring', 'Overnight Monitoring', 'Hospitalization with continuous monitoring.', 200, 450, 720 from public.service_categories where slug = 'emergency';
insert into public.services (category_id, slug, name, description, price_from, price_to, duration_minutes) select id, 'after-hours-consultation', 'After-Hours Consultation', 'Phone triage line for existing clients.', 0, 45, 15 from public.service_categories where slug = 'emergency';

insert into public.subscription_tiers (slug, name, price_monthly, tagline, features, sort_order) values ('essential', 'Essential', 19, 'For healthy pets that just need the basics covered.', '["1 wellness exam per year","10% off vaccinations","Member-only booking priority","Email appointment reminders"]'::jsonb, 0);
insert into public.subscription_tiers (slug, name, price_monthly, tagline, features, sort_order) values ('wellness', 'Wellness Plus', 39, 'Our most popular plan for ongoing preventive care.', '["2 wellness exams per year","20% off vaccinations & dental cleanings","Free annual bloodwork panel","Priority booking + same-week appointments","24/7 after-hours triage line"]'::jsonb, 1);
insert into public.subscription_tiers (slug, name, price_monthly, tagline, features, sort_order) values ('complete', 'Complete Care', 69, 'Comprehensive coverage for senior pets or multi-pet households.', '["Unlimited wellness exams","30% off surgery, dental & imaging","Free annual bloodwork + urinalysis","Dedicated care coordinator","24/7 after-hours triage line","Multi-pet discount eligible"]'::jsonb, 2);

